// Code generated by mockery v2.14.0. DO NOT EDIT.

package pubsubsink

import (
	context "context"

	pubsub "cloud.google.com/go/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// MockTopicGateway is an autogenerated mock type for the TopicGateway type
type MockTopicGateway struct {
	mock.Mock
}

type MockTopicGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopicGateway) EXPECT() *MockTopicGateway_Expecter {
	return &MockTopicGateway_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: ctx
func (_m *MockTopicGateway) Exists(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicGateway_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockTopicGateway_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//  - ctx context.Context
func (_e *MockTopicGateway_Expecter) Exists(ctx interface{}) *MockTopicGateway_Exists_Call {
	return &MockTopicGateway_Exists_Call{Call: _e.mock.On("Exists", ctx)}
}

func (_c *MockTopicGateway_Exists_Call) Run(run func(ctx context.Context)) *MockTopicGateway_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTopicGateway_Exists_Call) Return(_a0 bool, _a1 error) *MockTopicGateway_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Publish provides a mock function with given fields: ctx, msg
func (_m *MockTopicGateway) Publish(ctx context.Context, msg *pubsub.Message) PublishResult {
	ret := _m.Called(ctx, msg)

	var r0 PublishResult
	if rf, ok := ret.Get(0).(func(context.Context, *pubsub.Message) PublishResult); ok {
		r0 = rf(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PublishResult)
		}
	}

	return r0
}

// MockTopicGateway_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockTopicGateway_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//  - ctx context.Context
//  - msg *pubsub.Message
func (_e *MockTopicGateway_Expecter) Publish(ctx interface{}, msg interface{}) *MockTopicGateway_Publish_Call {
	return &MockTopicGateway_Publish_Call{Call: _e.mock.On("Publish", ctx, msg)}
}

func (_c *MockTopicGateway_Publish_Call) Run(run func(ctx context.Context, msg *pubsub.Message)) *MockTopicGateway_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pubsub.Message))
	})
	return _c
}

func (_c *MockTopicGateway_Publish_Call) Return(_a0 PublishResult) *MockTopicGateway_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

// Stop provides a mock function with given fields:
func (_m *MockTopicGateway) Stop() {
	_m.Called()
}

// MockTopicGateway_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTopicGateway_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockTopicGateway_Expecter) Stop() *MockTopicGateway_Stop_Call {
	return &MockTopicGateway_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockTopicGateway_Stop_Call) Run(run func()) *MockTopicGateway_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopicGateway_Stop_Call) Return() *MockTopicGateway_Stop_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewMockTopicGateway interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTopicGateway creates a new instance of MockTopicGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTopicGateway(t mockConstructorTestingTNewMockTopicGateway) *MockTopicGateway {
	mock := &MockTopicGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
